<?php use App\Core\Lang; ?><?= Lang::get('lang_es') === 'Español' ? 'Notificación de Conformidad' : 'Satisfaction Notification' ?> - PQRSF #<?= $pqrsfId ?>


<?= Lang::get('lang_es') === 'Español' ? 'Se ha registrado una respuesta de conformidad para el caso' : 'A satisfaction response has been registered for case' ?> #<?= $pqrsfId ?>


<?= Lang::get('lang_es') === 'Español' ? 'Fecha:' : 'Date:' ?> <?= $fecha ?>

<?= Lang::get('lang_es') === 'Español' ? 'Conforme:' : 'Satisfied:' ?> <?= $conformidadText ?>


<?php if ($conformidad === 'no' && !empty($motivo)): ?>
<?= Lang::get('lang_es') === 'Español' ? 'Motivo de inconformidad:' : 'Reason for dissatisfaction:' ?>
<?= $motivo ?>


<?php endif; ?>
========================================

<?= Lang::get('lang_es') === 'Español' ? 'Este es un mensaje automático generado por el sistema SIMCO.' : 'This is an automatic message generated by the SIMCO system.' ?>
