<?php use App\Core\Lang; ?><!DOCTYPE html>
<html lang="<?php echo Lang::get('lang_es') === 'Español' ? 'es' : 'en'; ?>">
<head>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f9fafb;
        }
        .header {
            background-color: #1e3a8a;
            color: white;
            padding: 20px;
            text-align: center;
            border-radius: 8px 8px 0 0;
        }
        .content {
            background-color: white;
            padding: 30px;
            border-radius: 0 0 8px 8px;
        }
        .info-box {
            background-color: #f0f4ff;
            padding: 15px;
            margin: 20px 0;
            border-left: 4px solid #1e3a8a;
            border-radius: 4px;
        }
        .conformidad-si {
            color: #16a34a;
            font-weight: bold;
        }
        .conformidad-no {
            color: #dc2626;
            font-weight: bold;
        }
        .motivo-box {
            background-color: #fef2f2;
            padding: 15px;
            border-left: 4px solid #dc2626;
            margin-top: 10px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h2><?= Lang::get('lang_es') === 'Español' ? 'Notificación de Conformidad' : 'Satisfaction Notification' ?></h2>
            <p>PQRSF #<?= $pqrsfId ?></p>
        </div>
        <div class="content">
            <p><?= Lang::get('lang_es') === 'Español' ? 'Se ha registrado una respuesta de conformidad para el caso' : 'A satisfaction response has been registered for case' ?> <strong>#<?= $pqrsfId ?></strong></p>
            
            <div class="info-box">
                <p><strong><?= Lang::get('lang_es') === 'Español' ? 'Fecha de respuesta:' : 'Response Date:' ?></strong> <?= $fecha ?></p>
                <p><strong><?= Lang::get('lang_es') === 'Español' ? 'Conforme con la respuesta:' : 'Satisfied with the response:' ?></strong> <span class="conformidad-<?= $conformidad ?>"><?= $conformidadText ?></span></p>
                
                <?php if ($conformidad === 'no' && !empty($motivo)): ?>
                <p><strong><?= Lang::get('lang_es') === 'Español' ? 'Motivo de inconformidad:' : 'Reason for dissatisfaction:' ?></strong></p>
                <div class="motivo-box">
                    <?= nl2br(htmlspecialchars($motivo)) ?>
                </div>
                <?php endif; ?>
            </div>
            
            <p style="margin-top: 30px; font-size: 12px; color: #6b7280;">
                <?= Lang::get('lang_es') === 'Español' ? 'Este es un mensaje automático generado por el sistema SIMCO. Por favor, revise el caso y tome las acciones necesarias.' : 'This is an automatic message generated by the SIMCO system. Please review the case and take necessary action.' ?>
            </p>
        </div>
    </div>
</body>
</html>
